# Generated by Django 5.1.1 on 2024-09-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_img'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='titulo',
            field=models.CharField(default='Meu Compromisso', max_length=250),
        ),
    ]
